apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 5  # 복제본 2개
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project-web
        image: 211.183.3.199/leejoohyun/project:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

#로드 밸런서 작성하기1
---
apiVersion: v1
kind: Service
metadata:
  name: project-svc
spec:
  selector:
    app: projects
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
